DEV := buzzer
DD := driver
APP := test
TFTPDIR := /tftpboot
CC = /opt/toolchains/arm-2014.05/bin/arm-none-linux-gnueabi-gcc

obj-m := $(DD).o

KDIR := /root/work/achroimx6q/kernel
PWD := $(shell pwd)

all :	$(DD) $(APP)

$(DD):	$(DD).c
	$(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules ARCH=arm

$(APP):	$(APP).c
	$(CC) -pthread -o $(APP) $(APP).c

install:
	cp -a $(DD).ko $(APP) $(TFTPDIR)

clean:
	rm -rf *.ko *.mod.* *.order *.symvers *.o $(APP)

new:
	$(MAKE) clean
	$(MAKE)